name = "egm"
type = "javascript"

[build]
command = "npm install --legacy-peer-deps && npm run build"
upload = { format = "directory", path = "./dist" }

[env.production]
pages_build_output_dir = "dist"
